name: "Lookup Table Action POC"
description: "Get Lookup Table Value"
inputs:
  TableName:
    description: "Name of the lookup table"
    required: true
    default: "Business"
  Query:
    description: "Lookup table query"
    required: false
    default: ""
  Column:
    description: "Name of the column"
    required: false
    default: "BusinessName"
runs:
  using: "composite"
  steps:
    - name: Check out action repo
      uses: actions/checkout@main
      with:
        repository: joshinagesh/PowerShell-Action-Demo
    - name: Get Lookup Table Value
      shell: pwsh
      run: ./Get-LookupTableOutput.ps1 -TableName ${{ inputs.TableName }} -Query ${{ inputs.Query }} -Column ${{ inputs.Column }}
