name: "Lookup Table Action POC"
description: "Get Lookup Table Value"
inputs:
  TableName:
    description: "Name of the lookup table"
    required: true
    default: "Business"
  Query:
    description: "Lookup table query"
    required: false
  Column:
    description: "Name of the column"
    required: false
    default: "BusinessName"
outputs:
  LookupTableValue:
    description: "Lookup Value"
    value: ${{ steps.fetch-lookup-value.outputs.LookupValue }}
runs:
  using: "composite"
  steps:
    - name: Check out action repo
      uses: actions/checkout@main
      with:
        repository: joshinagesh/PowerShell-Action-Demo
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Get Lookup Table Value
      id: fetch-lookup-value
      shell: pwsh
      run: ./Get-LookupTableOutput.ps1 -TableName ${{ inputs.TableName }} -Query ${{ inputs.Query }} -Column ${{ inputs.Column }}
    - run: echo "${{ steps.fetch-lookup-value.outputs.LookupValue }}"
      shell: bash
