name: "Lookup Table Action POC"
description: "Get Lookup Table Value"
inputs:
  TableName:
    description: "Name of the lookup table"
    required: true
    default: ""
  Query:
    description: "Lookup table query"
    required: false
    default: ""
  Column:
    description: "Name of the column"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Get Lookup Table Value
      shell: pwsh
      run: ./Actions/Get-LookupTableOutput.ps1 -TableName "Subscription" -Query "" -Column "SubscriptionId"
